//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./src/MIDL.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMIDLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MIDLBaseListener : IMIDLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecification([NotNull] MIDLParser.SpecificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecification([NotNull] MIDLParser.SpecificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinition([NotNull] MIDLParser.DefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinition([NotNull] MIDLParser.DefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule([NotNull] MIDLParser.ModuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule([NotNull] MIDLParser.ModuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.type_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_decl([NotNull] MIDLParser.Type_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.type_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_decl([NotNull] MIDLParser.Type_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.struct_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_type([NotNull] MIDLParser.Struct_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.struct_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_type([NotNull] MIDLParser.Struct_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.member_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_list([NotNull] MIDLParser.Member_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.member_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_list([NotNull] MIDLParser.Member_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.type_spec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_spec([NotNull] MIDLParser.Type_specContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.type_spec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_spec([NotNull] MIDLParser.Type_specContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.scoped_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScoped_name([NotNull] MIDLParser.Scoped_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.scoped_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScoped_name([NotNull] MIDLParser.Scoped_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.base_type_spec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBase_type_spec([NotNull] MIDLParser.Base_type_specContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.base_type_spec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBase_type_spec([NotNull] MIDLParser.Base_type_specContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.floating_pt_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloating_pt_type([NotNull] MIDLParser.Floating_pt_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.floating_pt_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloating_pt_type([NotNull] MIDLParser.Floating_pt_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.integer_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger_type([NotNull] MIDLParser.Integer_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.integer_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger_type([NotNull] MIDLParser.Integer_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.signed_int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSigned_int([NotNull] MIDLParser.Signed_intContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.signed_int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSigned_int([NotNull] MIDLParser.Signed_intContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.unsigned_int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnsigned_int([NotNull] MIDLParser.Unsigned_intContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.unsigned_int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnsigned_int([NotNull] MIDLParser.Unsigned_intContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.declarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarators([NotNull] MIDLParser.DeclaratorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.declarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarators([NotNull] MIDLParser.DeclaratorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarator([NotNull] MIDLParser.DeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarator([NotNull] MIDLParser.DeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.simple_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_declarator([NotNull] MIDLParser.Simple_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.simple_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_declarator([NotNull] MIDLParser.Simple_declaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.array_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_declarator([NotNull] MIDLParser.Array_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.array_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_declarator([NotNull] MIDLParser.Array_declaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.exp_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_list([NotNull] MIDLParser.Exp_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.exp_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_list([NotNull] MIDLParser.Exp_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_expr([NotNull] MIDLParser.Or_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_expr([NotNull] MIDLParser.Or_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.xor_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXor_expr([NotNull] MIDLParser.Xor_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.xor_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXor_expr([NotNull] MIDLParser.Xor_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expr([NotNull] MIDLParser.And_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expr([NotNull] MIDLParser.And_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.shift_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShift_expr([NotNull] MIDLParser.Shift_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.shift_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShift_expr([NotNull] MIDLParser.Shift_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.add_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_expr([NotNull] MIDLParser.Add_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.add_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_expr([NotNull] MIDLParser.Add_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.mult_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMult_expr([NotNull] MIDLParser.Mult_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.mult_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMult_expr([NotNull] MIDLParser.Mult_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.unary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expr([NotNull] MIDLParser.Unary_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.unary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expr([NotNull] MIDLParser.Unary_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] MIDLParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] MIDLParser.LiteralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
