module A
{
    module innerModule
    {
		struct internal
		{
			short c1 = "a";
			short i1=10;
			int16 i2=10;
		};
    };

    struct innerStruct
    {
		long i3=100;
		int32 i4=100;
		innerModule::internal test;
    };

};

module B
{
	module middle
	{
		module inner
		{
			struct bottom
			{
				unsigned short i7=10;
				uint16 i8=10;
				uint32 i10=100;
				long long i5=1000;
				int64 i6=1000;
				unsigned long i9=100;
			};
		};

	};

};

struct C
{
	short arr1 = "a";
	unsigned long long i11=1000;
	uint64 i12=1000;
	char c0='a';
	string c1="abc";
	boolean c2=true;
	float c3=10.901f;
	double c4=23.234d;
	long double c5=12.23456432235d;
	short arr[10]={0,1,2,3,4,5,6,7,8,9};
	C testBool1;
	A::innerModule::internal testBool2;
	int16 testInt = 2 + 5 * 2 / 3;
	float testFloat = 1.2 * 3.0 - 2.0 % 1.0;
	float testFloat2 = ~2.0;
};