//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./src/MIDL.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MIDLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMIDLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecification([NotNull] MIDLParser.SpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecification([NotNull] MIDLParser.SpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinition([NotNull] MIDLParser.DefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinition([NotNull] MIDLParser.DefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule([NotNull] MIDLParser.ModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule([NotNull] MIDLParser.ModuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_decl([NotNull] MIDLParser.Type_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_decl([NotNull] MIDLParser.Type_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.struct_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_type([NotNull] MIDLParser.Struct_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.struct_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_type([NotNull] MIDLParser.Struct_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_list([NotNull] MIDLParser.Member_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_list([NotNull] MIDLParser.Member_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_spec([NotNull] MIDLParser.Type_specContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_spec([NotNull] MIDLParser.Type_specContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.scoped_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScoped_name([NotNull] MIDLParser.Scoped_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.scoped_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScoped_name([NotNull] MIDLParser.Scoped_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.base_type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase_type_spec([NotNull] MIDLParser.Base_type_specContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.base_type_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase_type_spec([NotNull] MIDLParser.Base_type_specContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.floating_pt_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloating_pt_type([NotNull] MIDLParser.Floating_pt_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.floating_pt_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloating_pt_type([NotNull] MIDLParser.Floating_pt_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.integer_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger_type([NotNull] MIDLParser.Integer_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.integer_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger_type([NotNull] MIDLParser.Integer_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.signed_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSigned_int([NotNull] MIDLParser.Signed_intContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.signed_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSigned_int([NotNull] MIDLParser.Signed_intContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.unsigned_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnsigned_int([NotNull] MIDLParser.Unsigned_intContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.unsigned_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnsigned_int([NotNull] MIDLParser.Unsigned_intContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarators([NotNull] MIDLParser.DeclaratorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.declarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarators([NotNull] MIDLParser.DeclaratorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator([NotNull] MIDLParser.DeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator([NotNull] MIDLParser.DeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.simple_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_declarator([NotNull] MIDLParser.Simple_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.simple_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_declarator([NotNull] MIDLParser.Simple_declaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.array_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_declarator([NotNull] MIDLParser.Array_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.array_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_declarator([NotNull] MIDLParser.Array_declaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.exp_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_list([NotNull] MIDLParser.Exp_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.exp_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_list([NotNull] MIDLParser.Exp_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.or_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr_expr([NotNull] MIDLParser.Or_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.or_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr_expr([NotNull] MIDLParser.Or_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.xor_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXor_expr([NotNull] MIDLParser.Xor_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.xor_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXor_expr([NotNull] MIDLParser.Xor_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_expr([NotNull] MIDLParser.And_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_expr([NotNull] MIDLParser.And_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.shift_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShift_expr([NotNull] MIDLParser.Shift_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.shift_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShift_expr([NotNull] MIDLParser.Shift_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.add_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd_expr([NotNull] MIDLParser.Add_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.add_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd_expr([NotNull] MIDLParser.Add_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.mult_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMult_expr([NotNull] MIDLParser.Mult_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.mult_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMult_expr([NotNull] MIDLParser.Mult_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_expr([NotNull] MIDLParser.Unary_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_expr([NotNull] MIDLParser.Unary_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MIDLParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] MIDLParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MIDLParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] MIDLParser.LiteralContext context);
}
